version: '3'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongoDB
    restart: always
    ports:
      - "27017:27017"

  library:
    container_name: library-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo_db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=library
    restart: always
    depends_on:
      - mongo_db